import Header from "@/components/Header";
import { css, cx } from "@linaria/core";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const globalStyle = css`
    box-sizing: border-box;
    padding: 0;
    margin: 0;
    font-family: sans-serif;
  `;

  return (
    <html lang="en">
      <body className={cx(globalStyle)}>
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
